version: '3'
services:
        #flaskapp:
        #       build: ../try2/
        #       restart: always
        rides:
            restart: always
            image: rides:latest
            build: .
            volumes:
              - .:/opt/services/flaskappr/src
            networks:
              - web_nw
            entrypoint: ["python", "appr.py","runserver"]
            environment:
                    - TEAM_NAME=CC_0749_1674
        nginx:
            restart: always
            image: "nginx:1.13.5"
            ports:
              - "8000:80"
            volumes:
              - ./conf.d:/etc/nginx/conf.d
            networks:
              - web_nw
            depends_on:
              - rides
networks:
   web_nw:
    driver: bridge
